### PR TITLE
added index with background image and added big text

### PR DESCRIPTION
**Pull request by SlideChaser**
Added an index page, and css sheet

### CODE REVIEW

**Comment by SlideChaser** [comment]
I made a quick page, it has bootstrap on CDN, and a style sheet so we have our background/parallax

**Comment by esmiie** [comment]
Just checking to see what this will do after I leave the review.

**Comment by amyeyt** [comment]
uh here is a review?

**Review by esmiie — APPROVED** [review]
I am approving to see what will happen.

**Review by amyeyt — APPROVED** [review]

**Pull request merged**
